### PR TITLE
Urls like /?query=arg not correctly serving index

### PR DESCRIPTION
**Pull request by hcldan**

### CODE REVIEW

**Comment by hcldan** [comment]
@tkoenig89

**Comment by tkoenig89** [comment]
@hcldan thanks for your contribution. Do you mind adding a unit test for your case, so we can ensure it works properly with future changes? I think some alternation of the existing 'should handle index option...' tests should work. Thanks

**Comment by hcldan** [comment]
@tkoenig89 All set
Also, I tried to run `npm test` and I got a few failures (not the new test).  So hopefully this works for you fine, I didn't have time to dig.

**Comment by tkoenig89** [comment]
@hcldan thanks for adding the test. 

I had some failing tests localy as well a few weeks ago. But the checks in git ran fine. Maybe we have more recent node versions localy while git is only running tests vor 8,10,12. I need to look into this some time.

**Comment by tkoenig89** [comment]
@hcldan your changes are published with version 2.1.7.
Thanks again!

**Pull request merged**
